# render.yaml para Evolution API con Postgres gestionado y Redis (Key-Value) en Render
# Versión optimizada sin dependsOn, con health check y buenas prácticas

services:
  - type: web
    name: evolution-api
    env: docker
    # Si la imagen viene de tu Dockerfile en el repo
    rootDir: .
    plan: standard
    region: oregon

    # Comando para construir y arrancar (ajusta si ya usas imagen de Registry)
    # Si usas `image:` omití esta sección
    buildCommand: docker build . -t evolution-api
    startCommand: ./wait-for-services.sh && docker run --rm -p 8080:8080 evolution-api

    # Health check: endpoint que responde ok, para que Render sepa que la API está lista
    healthCheckPath: /health

    envVars:
      - key: AUTHENTICATION_API_KEY
        sync: false
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_PROVIDER
        value: "postgresql"
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolutiondb
          property: connectionString
      - key: DATABASE_CONNECTION_CLIENT_NAME
        value: evolution_exchange
      - key: DATABASE_SAVE_DATA_INSTANCE
        value: "true"
      - key: DATABASE_SAVE_DATA_NEW_MESSAGE
        value: "true"
      - key: DATABASE_SAVE_MESSAGE_UPDATE
        value: "true"
      - key: DATABASE_SAVE_DATA_CONTACTS
        value: "true"
      - key: DATABASE_SAVE_DATA_CHATS
        value: "true"
      - key: DATABASE_SAVE_DATA_LABELS
        value: "true"
      - key: DATABASE_SAVE_DATA_HISTORIC
        value: "true"
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        fromService:
          type: keyvalue
          name: evolution-redis
          property: internalURL  # puede ser `connectionString` o `internalURL` dependiendo del tipo
      - key: CACHE_REDIS_PREFIX_KEY
        value: evolution
      - key: CACHE_REDIS_SAVE_INSTANCES
        value: "false"
      - key: CACHE_LOCAL_ENABLED
        value: "false"
      - key: CONFIG_SESSION_PHONE_VERSION
        value: "2.3000.1023204200"
    # Opcional: parámetro para shutdown grace-period
    maxShutdownDelaySeconds: 60

  - type: keyvalue
    name: evolution-redis
    plan: starter
    region: oregon
    # No necesitas healthCheckPath para KeyValue, sólo para servicios web

databases:
  - name: evolutiondb
    plan: starter
    region: oregon

