# render.yaml corregido

services:
  - type: web
    name: evolution-api
    env: docker
    rootDir: .
    plan: standard
    region: oregon

    # No usar startCommand cuando env: docker
    # Asume que el Dockerfile define ENTRYPOINT o CMD correctos

    healthCheckPath: /health

    envVars:
      - key: AUTHENTICATION_API_KEY
        sync: false
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_PROVIDER
        value: "postgresql"
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolutiondb
          property: connectionString
      - key: DATABASE_CONNECTION_CLIENT_NAME
        value: evolution_exchange
      - key: DATABASE_SAVE_DATA_INSTANCE
        value: "true"
      - key: DATABASE_SAVE_DATA_NEW_MESSAGE
        value: "true"
      - key: DATABASE_SAVE_MESSAGE_UPDATE
        value: "true"
      - key: DATABASE_SAVE_DATA_CONTACTS
        value: "true"
      - key: DATABASE_SAVE_DATA_CHATS
        value: "true"
      - key: DATABASE_SAVE_DATA_LABELS
        value: "true"
      - key: DATABASE_SAVE_DATA_HISTORIC
        value: "true"
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        fromService:
          type: keyvalue
          name: evolution-redis
          property: connectionString   # Cambiado desde internalURL a connectionString
      - key: CACHE_REDIS_PREFIX_KEY
        value: evolution
      - key: CACHE_REDIS_SAVE_INSTANCES
        value: "false"
      - key: CACHE_LOCAL_ENABLED
        value: "false"
      - key: CONFIG_SESSION_PHONE_VERSION
        value: "2.3000.1023204200"

  - type: keyvalue
    name: evolution-redis
    plan: starter
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0    # permitir todo (o ajustar a las IPs externas que necesites)
        description: allow all
    # omitir healthCheckPath aquí

databases:
  - name: evolutiondb
    plan: starter
    region: oregon
